import { Product, ProductCategory } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Ultimate Stationery Set 5 in 1',
    price: 150,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTZ2Wo_P7U9E4rdZoJoW3DkFA1GA8vqnKkNGj1dTZBp-NaUcwvmlCMegIjYzfR4dUrctfby1FQzMFtzRROd-H_Hblqx0qLoksoX0X8WGVUv',
    description: 'Discover the 5-in-1 Ultimate Stationery Set perfect for school, office & gifts! Fun designs, premium quality & ideal return gift choice for all occasions.',
    stock: 25,
    category: ProductCategory.Stationery,
  },
  {
    id: 2,
    name: 'Graphite Pencil',
    price: 15,
    imageUrl: 'https://inkarto.com/cdn/shop/files/WhatsAppImage2025-10-26at5.14.18PM_3.jpg?v=1761479465&width=1100',
    description: 'A pencil that you have never experienced before, i.e., smoother and faster than others.',
    stock: 40,
    category: ProductCategory.Stationery,
  },
  {
    id: 4,
    name: 'Mechanical Pencil Set',
    price: 18.00,
    imageUrl: 'https://i.pinimg.com/736x/65/64/90/656490354684ddffd2c2176ac0a98cfc.jpg',
    description: 'Professional 0.5mm mechanical pencil with lead refills and erasers.',
    stock: 60,
    category: ProductCategory.Stationery,
  },
  {
    id: 5,
    name: 'Desktop Organizer',
    price: 199,
    imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTxNbmutXsKJTiJ_L-sMmVfwtjdoHM1mBQOzer87_ih7pQynE-_RhBZKxzHWlurAb_DSlEtM76xJjhGNmaWwbAZgph7BP_xnucr2RRREyk',
    description: 'Bamboo desktop organizer with multiple compartments for pens, notes, and supplies.',
    stock: 30,
    category: ProductCategory.Stationery,
  },
  {
    id: 6,
    name: 'Pastel Sticky Notes Set',
    price: 50,
    imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQQ3d1VzNjBUqPXdqshU2fPq2laPgjaxkXPlCmDhhgFdwmwkuKWYGjCDnPszibkj0s5EtMDgGJNMVjd8i9eKgORoRRWK7ItN2D-HP_YoMkm',
    description: 'Set of 6 uniquely shaped sticky note pads in pastel colors.',
    stock: 150,
    category: ProductCategory.Stationery,
  },
  {
    id: 7,
    name: 'Calligraphy Ink (Black)',
    price: 12.00,
    imageUrl: 'https://i0.wp.com/thepostmansknock.com/wp-content/uploads/2019/08/6oz_Sumi_Product.jpg?resize=736%2C736&ssl=1',
    description: 'Rich, waterproof black ink for fountain pens and dip pens.',
    stock: 50,
    category: ProductCategory.Stationery,
  },
  {
    id: 8,
    name: 'High-Quality Sketchbook',
    price: 65,
    imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR8ZUeM1jL08nFtB4b7j7669XKxgKNz8i8KKGk9FCyAJ7imSuF6ROlubx6hFPX-wdzdc1pjNWywn7NGZeytcEjsgKg4mN5Y4iuWXlwRaz8F2QPzUBuKrNZfPLM',
    description: 'Hardcover sketchbook with thick, bleed-proof paper for various media.',
    stock: 35,
    category: ProductCategory.Stationery,
  },
  {
    id: 9,
    name: 'Fresh Apples (1kg)',
    price: 80,
    imageUrl: 'https://www.foodandwine.com/thmb/ozENq23ZVI5_28hMhKDlzk42bVU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Apples-2000-b2f9fdb866fe4ca59a195782468816d1.jpg',
    description: 'Crisp and juicy red apples, perfect for a healthy snack.',
    stock: 100,
    category: ProductCategory.Fruit,
  },
  {
    id: 10,
    name: 'Whole Wheat Bread',
    price: 45,
    imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/2020-02/the-easiest-loaf-of-bread-youll-ever-bake.jpg',
    description: 'Soft and nutritious whole wheat bread, ideal for sandwiches.',
    stock: 75,
    category: ProductCategory.Grocery,
  },
  {
    id: 11,
    name: 'Organic Milk (1L)',
    price: 60,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRsEoVSM9IL4_nOvIokpBEr7RHqjYc9vPTTyppttfzD_2hJ4dVNFhNn9RampomZtOFOKPO8XbFT-HUawGKpuAxEPUVDxPg0zoxdeDqRhQ0',
    description: 'Fresh organic cow milk, rich in calcium and vitamins.',
    stock: 50,
    category: ProductCategory.Grocery,
  },
  {
    id: 12,
    name: 'Brown Eggs (Dozen)',
    price: 70,
    imageUrl: 'https://www.sanjayfarmproducts.com/img/brown.jpg',
    description: 'Farm-fresh brown eggs, a great source of protein.',
    stock: 80,
    category: ProductCategory.Grocery,
  },
  {
    id: 13,
    name: 'Fresh Bananas chips',
    price: 30,
    imageUrl: 'https://themoonstore.in/cdn/shop/files/3.png?v=1724227968',
    description: 'Naturally sweet and rich in potassium, perfect for a quick energy boost.',
    stock: 150,
    category: ProductCategory.Fruit,
  },
  {
    id: 14,
    name: 'Cheddar Cheese Block (200g)',
    price: 120,
    imageUrl: 'https://dlecta.com/cdn/shop/files/100_cheddarblock1.jpg?v=1703935831',
    description: 'A block of rich and creamy cheddar cheese, great for slicing and grating.',
    stock: 60,
    category: ProductCategory.Grocery,
  },
  {
    id: 15,
    name: 'Plain Greek Yogurt (500g)',
    price: 90,
    imageUrl: 'https://images-cdn.ubuy.co.in/653e92c04e04760e4e5e7bd9-great-value-greek-plain-nonfat-yogurt.jpg',
    description: 'Thick and creamy plain Greek yogurt, high in protein.',
    stock: 45,
    category: ProductCategory.Grocery,
  },
  {
    id: 16,
    name: 'Ripe Tomatoes (1kg)',
    price: 50,
    imageUrl: 'https://cdn-prd-02.pnp.co.za/sys-master/images/he2/h0b/11125489926174/silo-product-image-v2-16Mar2023-184341-6009605841531-Straight_on-108322-9834_515Wx515H',
    description: 'Juicy and flavorful ripe tomatoes, essential for salads and cooking.',
    stock: 90,
    category: ProductCategory.Vegetable,
  },
  {
    id: 17,
    name: 'Boneless Chicken Breast (500g)',
    price: 250,
    imageUrl: 'https://cdn.zeptonow.com/production/tr:w-312,ar-500-500,pr-true,f-auto,q-80/cms/product_variant/802cd624-0b92-44f8-9cbf-a02ec231bec9.jpeg',
    description: 'Lean and tender boneless chicken breast, versatile for any recipe.',
    stock: 40,
    category: ProductCategory.Grocery,
  },
  {
    id: 18,
    name: 'Spaghetti Pasta (500g)',
    price: 95,
    imageUrl: 'https://m.media-amazon.com/images/I/71XmMHS4ItL._AC_UF894,1000_QL80_.jpg',
    description: 'Classic spaghetti pasta, perfect for your favorite Italian dishes.',
    stock: 120,
    category: ProductCategory.Grocery,
  },
  {
    id: 19,
    name: 'Tomato Pasta Sauce (400g)',
    price: 110,
    imageUrl: 'https://assets.gustibusalimentari.it/wp-content/uploads/2024/04/MOCKUP-Sugo-Pomodoro-Basilico-400g-GUSTIBUS-2023-2-800x800.png',
    description: 'Rich and flavorful tomato and basil pasta sauce.',
    stock: 80,
    category: ProductCategory.Grocery,
  },
  {
    id: 20,
    name: 'Extra Virgin Olive Oil (500ml)',
    price: 450,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSQggd0uoSx4MpvbNdBQWsVRkehvwwEOw3Rg&s',
    description: 'Cold-pressed extra virgin olive oil for dressings and cooking.',
    stock: 50,
    category: ProductCategory.Grocery,
  },
  {
    id: 21,
    name: 'Ground Coffee (250g)',
    price: 220,
    imageUrl: 'https://caramelly.in/cdn/shop/files/mr-viet-arabica-ground-coffee-250g-873388.jpg?v=1735270992',
    description: 'Aromatic and rich ground coffee beans for a perfect brew.',
    stock: 70,
    category: ProductCategory.Grocery,
  },
  {
    id: 22,
    name: 'Green Tea Bags (100 count)',
    price: 180,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDPSJRrbe-5bhXhDQv0ofITuZ46Vgjq0ivSQ&s',
    description: 'Refreshing and healthy green tea bags, rich in antioxidants.',
    stock: 100,
    category: ProductCategory.Grocery,
  },
  {
    id: 23,
    name: 'Breakfast Cereal (300g)',
    price: 150,
    imageUrl: 'https://m.media-amazon.com/images/I/71F3Gej0MqL.jpg',
    description: 'Crispy corn flakes, a classic and healthy start to your day.',
    stock: 90,
    category: ProductCategory.Grocery,
  },
  {
    id: 24,
    name: 'Luxury Fountain Pen',
    price: 1599,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0582/0819/0643/files/Montblanc_Taj_Mahal_480x480.webp?v=1702909003',
    description: 'Elegant black forest fountain pen with a fine nib for a smooth writing experience.',
    stock: 40,
    category: ProductCategory.Stationery,
  },
  {
    id: 25,
    name: 'Leather-bound Journal',
    price: 600,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0teBQqKz6bxFQXjnAbskU6v_4-3-GHq2WJw&s',
    description: 'A5 vintage-style leather journal with 200 pages of unlined paper.',
    stock: 55,
    category: ProductCategory.Stationery,
  },
  {
    id: 26,
    name: 'Highlighter Set (6-pack)',
    price: 120,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSIrFWTXnvz26gaLzQsoWeNT9k0slOsLd2HQ&s',
    description: 'Set of 6 assorted pastel highlighters with chisel tips.',
    stock: 120,
    category: ProductCategory.Stationery,
  },
  {
    id: 27,
    name: 'Washi Tape Collection',
    price: 250,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmZ_otbqZzZSjLm4OFxYnKvYgmNRDtRwcygw&s',
    description: 'A collection of 12 decorative washi tape rolls with various patterns.',
    stock: 80,
    category: ProductCategory.Stationery,
  },
  {
    id: 28,
    name: 'Professional Watercolor Set',
    price: 950,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_B0ndZ0KRp08mRNphMx7aN1BbmkyfM0XFhw&s',
    description: 'A set of 24 vibrant watercolor pans, perfect for artists of all levels.',
    stock: 30,
    category: ProductCategory.Stationery,
  },
  { 
    id: 29, 
    name: 'Potatoes (1kg)', 
    price: 40, 
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe9OUYhxOn0NNkR2LROrL5a_mwxaRPeeggIg&s', 
    description: 'Versatile and essential for many dishes.', 
    stock: 150,
    category: ProductCategory.Vegetable,
  },
  { 
    id: 30, 
    name: 'Onions (1kg)', 
    price: 50, 
    imageUrl: 'https://shop.coles.com.au/wcsstore/Coles-CAS/images/4/8/0/4803991-zm.jpg', 
    description: 'A staple ingredient for adding flavor to any meal.', 
    stock: 130,
    category: ProductCategory.Vegetable,
  },
  { 
    id: 31, 
    name: 'Carrots (500g)', 
    price: 35, 
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_VtPZGquA-hygElcuQDFRp6yNtsRuU6hKdg&s', 
    description: 'Sweet and crunchy carrots, great for snacks or cooking.', 
    stock: 100,
    category: ProductCategory.Vegetable,
  },
  
  { 
    id: 34, 
    name: 'Electric Pencil Sharpener', 
    price: 750, 
    imageUrl: 'https://cdn.schoolspecialty.com/0489c9c0-3991-4264-93ff-b1fe011660e2/2039320-20241003_A_JPG%20Output.jpg?width=700&height=700&fit=bounds&canvas=700,700&bg-color=ffffff', 
    description: 'Heavy-duty electric sharpener for a perfect point every time.', 
    stock: 25,
    category: ProductCategory.Stationery,
  },

  {
    id: 39,
    name: 'Classic Potato Chips',
    price: 20,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhtwUwjmgFv1ktKIxT-ziOnKpiBj082CqjUA&s',
    description: 'Crispy, classic salted potato chips. The perfect snack for any time.',
    stock: 200,
    category: ProductCategory.Grocery,
  },
  {
    id: 40,
    name: 'Roasted Almonds (250g)',
    price: 350,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjUJEPfSklEEwgEGrCXdOLQzOQdTx-bnp2mw&s',
    description: 'Healthy and delicious roasted almonds, lightly salted.',
    stock: 80,
    category: ProductCategory.Grocery,
  },
  {
    id: 41,
    name: 'Fresh Spinach (Bunch) ',
    price: 25,
    imageUrl: 'https://media.istockphoto.com/id/1159979911/photo/spinach-bunch-and-cutting-board-on-dark-grey-blackboard.jpg?s=612x612&w=0&k=20&c=bBIctps1pLcSjZyVN16COMyE_gLQP8E-jO_y59fHu4o=',
    description: 'A bunch of fresh, leafy green spinach, rich in iron.',
    stock: 70,
    category: ProductCategory.Vegetable,
  },
  {
    id: 42,
    name: 'Juicy Oranges (1kg)',
    price: 90,
    imageUrl: 'https://www.woolworths.co.za/images/elasticera/products/hero/2014-07-31/20025939_hero.jpg',
    description: 'Sweet and juicy oranges, bursting with Vitamin C.',
    stock: 120,
    category: ProductCategory.Fruit,
  },
  {
    id: 43,
    name: 'Lemon Dish Soap (500ml)',
    price: 85,
    imageUrl: 'https://m.media-amazon.com/images/I/51rhw--KcDL._AC_UF1000,1000_QL80_.jpg',
    description: 'Powerful dish soap with a fresh lemon scent. Cuts through grease easily.',
    stock: 100,
    category: ProductCategory.Grocery,
  },
  { 
    id: 44, 
    name: 'Orange Juice (1L)', 
    price: 130, 
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsM1rRnGwZJ4uKJftShmFpzc5SzcAjX5gcvQ&s', 
    description: 'Freshly squeezed orange juice, packed with Vitamin C.', 
    stock: 60,
    category: ProductCategory.Grocery,
  },
    { 
    id: 45, 
    name: 'Stainless Steel Ruler (30cm)', 
    price: 80, 
    imageUrl: 'https://raajkart.com/media/catalog/product/cache/378cf9a83101843e5b8b1271b991c285/w/h/whatsapp_image_2023-04-06_at_7.08.30_pm.jpeg', 
    description: 'Durable 30cm stainless steel ruler with metric and imperial markings.', 
    stock: 150,
    category: ProductCategory.Stationery,
  },
  { 
    id: 46, 
    name: 'Salted Butter (200g)', 
    price: 110, 
    imageUrl: 'https://m.media-amazon.com/images/I/61duEBwvXdL._AC_UF350,350_QL50_.jpg', 
    description: 'Creamy salted butter, perfect for baking and spreading.', 
    stock: 70,
    category: ProductCategory.Grocery,
  },
   { 
    id: 47, 
    name: 'Whiteboard Markers (4-pack)', 
    price: 150, 
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUjDjL3Cs4NCtSQoFeEJED6O40NMReu78CXA&s', 
    description: 'Set of 4 assorted dry-erase markers for whiteboards.', 
    stock: 110,
    category: ProductCategory.Stationery,
  },
   { 
    id: 48, 
    name: 'A4 Printer Paper (500 Sheets)', 
    price: 550, 
    imageUrl: 'https://m.media-amazon.com/images/I/41svaMqPXyL._AC_UF1000,1000_QL80_.jpg', 
    description: 'High-quality 80gsm A4 paper, ideal for printing and copying.', 
    stock: 80,
    category: ProductCategory.Stationery,
  },
  { 
    id: 49, 
    name: 'Desktop Stapler Set', 
    price: 300, 
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyfMz3x0cAvrAVugIJQwcz3kNPBYhdujm6iA&s', 
    description: 'Durable metal stapler with 1000 staples included.', 
    stock: 90,
    category: ProductCategory.Stationery,
  },
];